### ISSUE TITLE
Build script fails

### ISSUE THREAD

**Issue by alperunal** [maierfelix/emerald-engine#1]
Hello,

I could not build project. Can you write build & run information to README file? 

`npm run build`
command fails, here is dump:

`rollup -c rollup/rollup.config.cjs.js && rollup -c rollup/rollup.config.es.js
no such file or directory, lstat '/Users/alperunal/Dev/pokemon/emerald-engine/rollup/rollup.config.cjs.js'`

**Comment by maierfelix** [comment]
Hey there, I didn't touch this project for a long time, but as far as I remember right, I used `npm run browser` for building the client and `npm run server` to build the server.

**Comment by alperunal** [comment]
Thanks for quick response.
It worked, how to run?

**Comment by maierfelix** [comment]
Server is bundled in `dist/bundle-server`
Client in `dist/bundle-client`

I don't remember how to run the client - the client uses nw.js
The server requires mysql, I don't have the database anymore, but you should be able to re-build it on your own based on the login-server code e.g. [here](https://github.com/maierfelix/emerald-engine/blob/master/src/server/login-server/index.js#L261-L263)

No problem though I'm having hard times remembering the internals, can't help much on this.. :)

Edit: Oh and if you're curious:
[terrain-generator](https://github.com/maierfelix/emerald-engine/tree/master/src/terrain-generator) can generate infinite terrains based on the tile graphics extraced from the emerald ROM file
[rom-ts-editor](https://github.com/maierfelix/emerald-engine/tree/master/src/rom-ts-editor): Allows to create clean tilesets from the ROM file, because the raw tilesets inside the ROM are pretty messy to work with

**Comment by alperunal** [comment]
Ok, I'll take a look at this. Thanks for your help.
